[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=/var/local/sddm-wallpaper/background.jpg

# Material You-like colors (we can refine these)
primaryColor=#c0caf5
accentColor=#9ece6a
autoColor=true
use24HourClock=false
backgroundColor=#1a1b26
textColor=#c0caf5

# Font settings
fontFamily=JetBrainsMonoNerdFontMono-Regular
fontSize=14
