nautipad {
    class = org.gnome.Nautilus
    command = nautilus 
    options = persist pin
}

termpad {
    class = termpad
    command = kitty --class=termpad 
    options = persist pin
}

vimpad {
    class = vimpad
    command = kitty --class=vimpad -e nvim 
    options = persist pin
}

codipad {
    class = codipad
    command = codium 
    options = persist pin
}


# Optional globals that apply to all scratchpads
daemon_options = clean eager
global_options = persist pin
