
# File Explorer
nautipad {
    class = org.gnome.Nautilus 
    command = nautilus 
    options = persist
}

# Terminal
termpad {
    class = termpad
    command = kitty --class=termpad 
    options = persist
}

# Neovim
vimpad {
    class = vimpad
    command = kitty --class=vimpad -e nvim 
    options = persist
}

# VSS Code
codepad {
    class = codepad
    command = code 
    options = persist
}

# Arabic Keyboard Layout
osdpad {
    class = com.layout.viewer
    command = python ~/.config/xkb/symbols/my_ar.py
    options = lazy
}

# Optional globals that apply to all scratchpads
daemon_options = clean eager
global_options = persist
