-- Generated by HyprMon. Manual changes may be overwritten.

hl.monitor({ output = "DP-1", mode = "1920x1080@143.85", position = "-32x0", scale = 1.00, bitdepth = 10, cm = "auto", vrr = 2 })
hl.monitor({ output = "DP-2", mode = "1920x1080@200.00", position = "1888x0", scale = 1.00, cm = "auto" })
