-- Generated by HyprMon GTK. Manual changes may be overwritten.

hl.monitor({ output = "DP-1", mode = "1920x1080@143.85Hz", position = "0x0", scale = 1.00 })
hl.monitor({ output = "DP-2", mode = "1920x1080@200.00Hz", position = "1920x0", scale = 1.00 })
