nautipad {
    class = org.gnome.Nautilus
    command = nautilus 
    options = persist
}

termpad {
    class = termpad
    command = kitty --class=termpad 
    options = persist
}

vimpad {
    class = vimpad
    command = kitty --class=vimpad -e nvim 
    options = persist
}

codepad {
    class = codepad
    command = code 
    options = persist
}


# Optional globals that apply to all scratchpads
daemon_options = clean eager
global_options = persist
