foreground         #d8caac
background         #272e33
background_opacity 1.0
cursor             #d8caac

active_tab_foreground     #272e33
active_tab_background     #d8caac
inactive_tab_foreground   #d8caac
inactive_tab_background   #272e33

active_border_color   #d8caac
inactive_border_color #272e33
bell_border_color     #e67e80

color0       #272e33
color8       #868d80
color1       #e67e80
color9       #e67e80
color2       #a7c080
color10      #a7c080
color3       #dbbc7f
color11      #dbbc7f
color4       #7fbbb3
color12      #7fbbb3
color5       #d39bb6
color13      #d39bb6
color6       #83c092
color14      #83c092
color7       #859289
color15      #9da9a0
